# PLM6 - numpy, Pandas, mysql in Python, regular expressions

# numpy

Without numpy (a list). If we try to *sum* two lists we actually concatenate them:

In [1]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list1 + list2

[1, 2, 3, 4, 5, 6]

If we are interested in doing the sum of elements occupying the same position we should do:

In [2]:
list1[0] + list2[0]

5

To go through all elements we can use a for loop

In [3]:
list_sum = []
for i, _ in enumerate(list1):
    list_sum.append(list1[i] + list2[i])
list_sum

[5, 7, 9]

Notice the use of variable '_' in the previous cell. This is used when we need to define variables that we are not going to use. In this case enumerate gives pairs (number, elements); since we only care about the numbers and not the elements we assign the elements to '_'. This is a convention and everyone understands that the value in this variable is useless.

Remember list comprehensions. They are often a more concise way of getting the same result.

In [4]:
[list1[i] + list2[i] for i, _ in enumerate(list1)]

[5, 7, 9]

Let's convert the lists to numpy arrays using the array() function. But first let's import *numpy*. The convention is to import it with the alias *np*:


In [5]:
import numpy as np
array1 = np.array(list1)
array1

array([1, 2, 3])

With arrays we can indeed do element-wise sums

In [6]:
array2 = np.array([4, 5, 6])
array1 + array2

array([5, 7, 9])

*numpy* comes with very convinient functions such as **arange()** which creates an array with range of numbers

In [7]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

or **reshape() which allows to change the shape of the array to the dimensions provided, reshape(rows, columns) in the example:

In [8]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

If we only want to get one particular *row* we do:

In [9]:
arr = np.arange(12).reshape(3, 4)
arr[2]

array([ 8,  9, 10, 11])

If we want a specific cell we provide the *row* and the *column* numbers:

In [10]:
arr[2][1]

9

Because this is a very common operation there is an equivalent simplified notation:

In [11]:
arr[2, 1]

9

This also works for a range of rows (1:3) and a range of columns (2:4)

In [12]:
arr[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

As a particular case, if we want a single column we can do:

In [13]:
arr[:,2]

array([ 2,  6, 10])

This was not possible to do in a list of lists.

*numpy* also comes with all the relevant *statistical functions*:

In [14]:
np.mean(arr)

5.5

In [15]:
print(np.std(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))

3.452052529534663
5.5
0
11


In all these cases we can use either the whole array or a part of it:

In [16]:
print(np.mean(arr[2]), np.mean(arr[:,2]), np.mean(arr[1:,2:]))

9.5 6.0 8.5


*numpy arrays* permit filter within the elements of an array in a very straighforward manner. In this case elements > 8. The result is an array of *booleans* telling if each element matched the condition or not. 

In [17]:
arr_bol = arr > 8
print(arr)
print(arr_bol)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False False False False]
 [False  True  True  True]]


We can use the *array of booleans* (arr_bol) to filter the original array (arr). This is called *boolean indexing* because we use an array of booleans were we should use an index:

In [18]:
arr[arr_bol]

array([ 9, 10, 11])

But in fact there is no need to create this array of booleans as we can do it in one step:

In [19]:
arr[arr > 8]

array([ 9, 10, 11])

## pandas

We start importing *pandas* with the usual alias *pd*

In [20]:
import pandas as pd

We create a *dataframe object* from a *csv file* by using the **read_csv()** function.

In [ ]:
df = pd.read_csv('transmembrane_snp.csv', index_col='var_id')
df

Notice that *pandas* decided to hide part of the table for easier visualization. Check the type of the variable *df*:

In [ ]:
type(df)

Now some methods to start exploring a new dataframe. *.info()* is one of such methods. It gives us the list of columns in the dataframe, its type, number of non-nulls, ...


In [ ]:
df.info()

We can also explore the begining and the end of a dataframe:

In [ ]:
df.head()

In [ ]:
df.tail(3)

Or get the main statistical descriptors for all quantitative variables:

In [ ]:
df.describe()

Other functions are available such as:

In [ ]:
df.median()

To get a single colum of a dataframe we have 2 options. One is using dictionary notation:

In [ ]:
df['rs_id']

The second uses attribute notation:

In [ ]:
df.rs_id

When we select one column of a pandas Dataframe we get a pandas Series

In [ ]:
type(df.rs_id)

We can select more than one columne at once. We should provide a list with the column names:

In [ ]:
df[['freq_wt', 'freq_mut']]

If we would like one single value (cell) we use the column and index names:

In [ ]:
df['rs_id']['VAR_030596']

Another possibility is to use the column name and the index position (or range of positoins)

In [ ]:
df['rs_id'][10:15]  # part of a columns

If we are interested in rows we can access them via the *.loc* attribute if we provide the index name(s)

In [ ]:
df.loc['VAR_030596']  # row

In [ ]:
df.loc['VAR_055211':'VAR_030596']  # range of rows

In [ ]:
df.loc['VAR_055211','aa_wt']  # value

If instead we want to use the row numeric index we cna use the attribute *.iloc*

In [ ]:
df.iloc[0]  # first row

In [ ]:
df.iloc[:,0] # first column

We can specify a conditionand get a Series of booleans that tell which elements matched and which did not match the condition

In [ ]:
df['uniprot_name'] == 'GNHR_HUMAN'

We can next do boolean indexing, that is using the bool Series (filt) to filter the dataframe

In [ ]:
filt = df['uniprot_name'] == 'GNRHR_HUMAN'
df[filt]

Actually we could have done the same in one step

In [ ]:
df[df['uniprot_name'] == 'GNRHR_HUMAN']

We can create new columns from existing columns

In [ ]:
df['freq_dif'] = df['freq_wt'] - df['freq_mut']
df['freq_dif']

And we can draw nice plots directly from the dataframe object by using *matplotlib**

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df.plot(x='freq_wt', y='freq_mut', kind='scatter')
plt.show()

In [ ]:
df.plot(y='entropy', kind='hist')
plt.show()

In [ ]:
df.plot(y='freq_wt', kind='box')
plt.show()

In [ ]:
df[['freq_wt', 'freq_mut']].plot(kind='box')
plt.show()

## MySQL 

Since we did not install MySQL in our computer we will have to connect to **masteromics.uvic.cat** *DO NOT TRY TO RUN THE FOLLOWING CELL!*
Just login to masteromics.uvic.cat and work from there. 

In [ ]:
$ ssh pepe@masteromics.uvic.cat # replace pepe
$ mysql pepedb -p
# check that protein tables is ther and quit
$ ipython  # ipython is the text-based version of a Jupyter Notebook

import sqlalchemy
username = 'pepe'
password = 'omics1920'
database = 'pepedb'

engine = sqlalchemy.create_engine(f'mysql+mysqlconnector://{username}:{password}@localhost/{database}')
#results = engine.execute("SELECT * FROM proteins")
#data = results.fetchall()

import pandas as pd
df = pd.read_sql("SELECT uniprot_entry, gene_name FROM proteins", engine, index_col='uniprot_entry')
df
entries = df.index
genes = df.gene_name
zip(entries, genes)
list(zip(entries, genes))
dict(zip(entries, genes))
for entry, gene in zip(entries, genes): 
    print(entry, gene) 

## Regular expressions

We have previously used the *str.find()* method to find motifs in a sequence (substrings in a string)

In [ ]:
dna = 'GCTATATGTCCGAGCTA'  # should have CT and many As and Ts
dna.find('CT')

For more comples motifs we could use regular expressions. The **re** module is part of Python's *standard library*.

In [ ]:
import re
dir(re)

Notice thath there is a **search** function in this module. Let's see the *help* info.

In [ ]:
help(re.search)

Le'ts search the motif 'CT' in the sequence dna. Notice that this will only provide the first occurence of the motif.

In [ ]:
re.search('CT', dna)

We got a match object that tells that the first occurrence of the motif 'CT' is at dna[1:3]

In [ ]:
dna[1:3]

Remember that in a recular expression '.' means *any character*

In [ ]:
re.search('C.', dna)

You can see here that *match* gave as the specific string matched.

We can use [] to list possible allowed characters at a certain position (A or T) following C in this case:

In [ ]:
re.search('C[AT]', dna)

or four consecutive characters with A or T

In [ ]:
re.search('[AT]{4}', dna)  

or a motif with at list at least 4 at at most 6 As or Ts

In [ ]:
re.search('[AT]{4,6}', dna)

We can access the specific *match*, *starting position* and *ending position* individually using .group(), .start() and .end() methods in a match object.

In [ ]:
match = re.search('C.', dna)
print(match.group(), match.start(), match.end())

Let's take the DNA from a file:

In [ ]:
with open('dna.txt') as dna_file:
    dna = dna_file.read().strip()
motif = '[AT]{3,100}'

In [ ]:
re.search(motif, dna)

What if we want to find all occurrences of the regular expression? We can use **.findall()**

In [ ]:
re.findall(motif, dna)

But the previous function returns a list of matches without the positions where the matches were found.

If we want to have all the information we could use **.finditer()** instead.

In [ ]:
matches = re.finditer(motif, dna)
for match in matches:
    print(match)

This is a collection of *match* objects.

For nicer visualization We could also do:

In [ ]:
matches = re.finditer(motif, dna)
for match in matches:
    print(match.start(), match.end(), match.group())